## utak atik

no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
gradient_accumulation_steps = 16
gradient_checkpointing = false
huber_c = 0.05
huber_schedule = "exponential"
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
learning_rate = 0.001
loss_type = "huber"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 3
lr_scheduler_power = 1
max_bucket_reso = 1024
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 128
max_train_steps = 1
min_bucket_reso = 256
min_snr_gamma = 7
mixed_precision = "bf16"
network_alpha = 64
network_args = []
network_dim = 64
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_args = ["betas=(0.9,0.999)", "weight_decay=0.0"]
optimizer_type = "AdamW8bit"
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
prior_loss_weight = 1
resolution = "512,512"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 10
save_model_as = "safetensors"
save_precision = "bf16"
scale_weight_norms = 5
text_encoder_lr = [0.0, 0.0]
train_batch_size = 1
train_data_dir = ""
training_comment = ""
unet_lr = 0.001                                                                                                                                                             
xformers = true
